name: Manual actions workflow

on: 
    workflow_dispatch

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Say something
          run: echo"Hi, I have been triggered manually"