name: Manual actions workflow

on: 
    workflow_dispatch
jobs:
    manual_approval:
        name: Manual approval
        runs-on: ubuntu-latest
        steps:
            - name: Incrementing Build Version Name and Build Version Number
              run: |
               IFS='.' read -ra version_parts <<< "1.0.0"
               major="${version_parts[0]}"
               minor="${version_parts[1]}"
               patch="${version_parts[2]}"
               patch=$((patch))
               ((patch ++))
               patch_increased_version="$major.$minor.$patch"
               echo "$patch"
               echo "BUILD_VERSION_NAME=$patch_increased_version"
    