name: Manual actions workflow

on: 
    workflow_dispatch:
    push:
     branches:
          - main
jobs:
    manual_approval:
        name: Manual approval
        runs-on: ubuntu-latest
        steps:
        - name: Waiting for manual approval
          uses: trstringer/manual-approval@v1
          with:
            secret: '${{ github.token }}'
            approvers: SaikishorQube
            minimum-approvals: 1
            issue-title: "Publishing test Production Android & iOS build"
            issue-body: "Please approve or deny the publishing"